-- 1051h: ifr_2
Create table ifr_2(
    ifr_id  serial primary key,
    input_frequencyex float Check(input_frequencyex BETWEEN -1000 AND 1000),
    input_frequency float Check(input_frequency BETWEEN 0 AND 1000000000000),
    if_inputport integer Check(if_inputport IN(0,1)),
    ifr_opmode integer Check(ifr_opmode IN(0,1)),
    carrier_acquisition integer Check(carrier_acquisition IN(0,1)),
    loopf_bandwith integer,
    agctime_constant integer Check(agctime_constant IN(0,1,2,3,4)),
    contloopf_bandwith float,
    doppler_compifr integer Check(doppler_compifr IN(0,1)),
    dopplerdflow_id integer,
    spectdflow_id integer,
    carrier_acquisition_rangep float Check(carrier_acquisition_rangep BETWEEN 1000 AND 1000000),
    video_demomode integer Check(video_demomode IN(-1,0,1,2,3,4)),
    input_selection integer Check(input_selection BETWEEN 0 AND 9),
    afc integer Check(afc IN(0,1,2,3,4)),
    pcm_demomode integer Check(pcm_demomode BETWEEN -1 AND 10),
    dopp_samplingrate float Check(dopp_samplingrate BETWEEN 0.1 AND 10),
    dopp_measurenumber integer Check(dopp_measurenumber BETWEEN 1 AND 1000),
    spectanalysis_span integer Check(spectanalysis_span BETWEEN 0 AND 25),
    ifbandwith_filter integer Check(ifbandwith_filter BETWEEN 0 AND 15),
    predetection_filter integer Check(predetection_filter BETWEEN 0 AND 256),
    discriminator_adjust integer Check(discriminator_adjust BETWEEN 1 AND 16),
    video_filter integer Check(video_filter BETWEEN 0 AND 256 ),
    decoding_qpsk integer ,
    psk8_map integer,
    swap_ıq integer Check(swap_ıq IN(0,1)),
    ıq_ratio float Check(ıq_ratio BETWEEN -20 AND 20 ),
    carrier_tracrange float Check(carrier_tracrange BETWEEN 0 and 500000),
    loopf_bandwithacq float,
    carrier_offset float Check(carrier_offset BETWEEN -1000000 AND 1000000),
    if_rflevel float Check(if_rflevel BETWEEN -128 AND 127),
    pll_status integer Check(pll_status IN(0,1)),
    sampling_frequency integer Check(sampling_frequency IN(0,1,2,3,4,5,6)),
    current_spectanalysrange integer,
    demodulation integer,
    eb_no float Check(eb_no BETWEEN -128 AND 127 ),
    bitsynchronizer_status integer Check(bitsynchronizer_status IN(0,1)),
    frequency_dev float,
    if_inputrange integer Check(if_inputrange IN(0,1,2)),
    doppler_compstatus integer Check(doppler_compstatus IN(0,1,2,3)),
    doppstorage_status integer Check(doppstorage_status IN(0,1,2,4)),
    process_information integer
);

