-- 1060h: telemetry_unit_a
Create table tmu_a(
    tmu_id serial  primary key,
    bit_rate float CHECK(bit_rate BETWEEN 7 AND 40000000),
    symbol_ratedvb float Check(symbol_ratedvb BETWEEN 100 AND 20000000),
    subcarrier_frequency float  CHECK(subcarrier_frequency  BETWEEN 40 AND 2000000),
    pskdemod_bw integer CHECK(pskdemod_bw IN(0,1,2,3,4,5,6)),
    pcm_code integer CHECK(pcm_code BETWEEN 0 AND 12),
    word_mask integer,
    datadecoding_ccsds integer,
    viterbi_decoder integer,
    tcmhigh_bandwith integer,
    readsolomon_decoding integer CHECK(readsolomon_decoding IN(0,1,2,3,4,5,6)),
    descrambling_mode integer CHECK(descrambling_mode IN(0,1,2,3,4,5)),
    frameblock_size integer CHECK(frameblock_size BETWEEN 10 AND 32000),
    sw integer,
    sw_length integer,
    tmu_opmode integer Check(tmu_opmode IN(0,1,2)),
    sync_threshold integer CHECK(sync_threshold BETWEEN 0 AND 63),
    ctl_threshold integer CHECK(ctl_threshold BETWEEN 0 AND 7),
    lts_threshold integer CHECK(lts_threshold BETWEEN 0 and 7),
    bitslip_window integer CHECK(bitslip_window IN(0,1,2)),
    frame_synchronizer integer CHECK(frame_synchronizer IN(0,1)),
    antifalselock_delay float,
    frame_checking integer CHECK(frame_checking IN(0,1,2)),
    crc_polynomial integer,
    crcpreset_value integer,
    baseline_comp integer CHECK(baseline_comp IN(0,1,2,3,4)),
    sw_lsb integer,
    sw_mask integer,
    bw_bitsync float,
    viterbi_decoder_inputfs integer CHECK(viterbi_decoder_inputfs IN(0,1,2,3,4)),
    matched_filter integer,
    matchednext_filter integer,
    rolloffactor_bts float CHECK(rolloffactor_bts BETWEEN 0.1 AND 1.0),
    bpsk_demodeinput integer CHECK(bpsk_demodeinput BETWEEN 0 AND 8),
    tmstorage_id integer,
    tmstorage_writenumber integer,
    subcarrier_type integer,
    tmu_type0 integer CHECK(tmu_type0 IN(0,3)),
    tmu_type1 integer CHECK(tmu_type1 In(0,1,3)),
    tmu_type2 integer CHECK(tmu_type2 IN(0,1,2,3)),
    testpoints_invertswap  integer CHECK(testpoints_invertswap IN(0,1,2,3)),
    testpoints_iq integer CHECK(testpoints_iq IN(0,1)),
    tp_dataencoding integer CHECK(tp_dataencoding IN(0,1,2,3,4,5)),
    fm_modes integer CHECK(fm_modes BETWEEN 0 AND 15),
    turbocode_rate integer CHECK(turbocode_rate IN(0,1,2,3,4)),
    ldpc_coderate integer CHECK(ldpc_coderate IN(0,1,2,3,4)),
    dvbs2_decoder integer,
    tpc_decoder integer CHECK(tpc_decoder IN(0,1)),
    timeoffset integer,
    doppler_compensation_tmu integer CHECK(doppler_compensation_tmu IN(0,1)),
    demode_index float CHECK(demode_index BETWEEN 0 and 3.14),
    framesize_transfer integer CHECK(framesize_transfer BETWEEN 10 and 32000),
    ebno float CHECK(ebno BETWEEN -128 and 127),
    syncbit_status integer CHECK(syncbit_status IN(0,1)),
    pskdemod_status integer CHECK(pskdemod_status IN(0,1)),
    frame_syncstatus integer,
    ldpc_status integer,
    utoa integer,
    bit_slip integer Check(bit_slip BETWEEN 0 and 2),
    viterbi_decoder_status integer Check(viterbi_decoder_status IN(0,1,2,3)),
    readsolomon_decoder_status integer,
    ldpc_decoder_status integer,
    dvbs2_channel integer,
    frame_check integer,
    readsolomon_depth integer,
    ldpc_decoder_itnumber integer,
    dvbs2_plbb integer,
    tmu_extension integer,
    tmstorage_files integer,
    tmstorage_filesize integer,
    tmutype integer CHECK(tmutype IN(0,1,3)),
    tmlisence integer,
    tmlisencenext integer,
    viterbi_decoderber float CHECK(viterbi_decoderber BETWEEN 0 and 1),
    ldpc_decoder_ber float CHECK(ldpc_decoder_ber BETWEEN 0 and 1 ),
    tmstoragefile_id integer,
    tmstorage_offsetfile integer,
    tmstorage integer CHECK(tmstorage IN(0,1,2,4)),
    readsolomon_decoder_ber float CHECK(readsolomon_decoder_ber BETWEEN 0 and 1),
    goodtransfer_framecounter integer,
    badtransfer_framecounter integer,
    subcarrier_frequencyoffset float CHECK(subcarrier_frequencyoffset BETWEEN -100000 AND 100000),
    symbol_ratefroffset float CHECK(symbol_ratefroffset BETWEEN -1000000 and 1000000),
    active_set_testpointsip integer,
    viterbi_decoderber_qchan float CHECK(viterbi_decoderber_qchan BETWEEN 0 and 1),
    dvbs2_counter integer,
    doppler_compensation_statustmu integer CHECK(doppler_compensation_statustmu IN(0,1,2,3)),
    telemetry_frametime integer CHECK(telemetry_frametime IN(0,1,2)),
    telemetrymessage_counter bigint  CHECK(telemetrymessage_counter BETWEEN 0 and 4294967295 ),
    tx_linkstatus integer CHECK(tx_linkstatus IN(0,1,2,3,16))
);
