Create table global_cortex(
gcu_id serial primary key,
mon_dataflow_id integer ,
log_dataflow_id integer,
ref_frequency_sel integer CHECK(ref_frequency_sel IN(0,1,2,3)),
leapyear_second integer,
currentoffset_time integer,
datenextoffset1_time integer,
nextoffset1_time integer,
nextoffset2_time integer,
video_tp_program1 integer CHECK(video_tp_program1 BETWEEN 0 AND 114),
time_code integer CHECK(time_code IN(0,1)),
reserv_compatibility integer,
video_tp_program2 integer CHECK(video_tp_program2 between 0 AND 114),
ifinputportconf1 integer,
ifinputportconf3 integer,
ifinputportconf5 integer,
reserv_dtr integer,
leapsecond_date integer,
cortexshelfid_ctxdocstatus integer,
cortex_opmode integer Check(cortex_opmode IN(0,1)),
tcu_tms integer,
tms_exmount integer,
rau_mount integer,
rau_ex_mount integer,
ifm integer,
ifr_dcu integer,
tmu integer,
noisegen_efcboard integer,
tmu_ifras integer,
time_alarm integer CHECK(time_alarm IN(0,1)),
dtr_reserved integer,
pps_external1 integer,
tcu_tms_alarm integer,
tru_mounted integer,
ifm_alarm integer ,
ifr_alarm integer ,
tmu_alarm integer,
noise_generator integer CHECK(noise_generator IN(0,1)),
fpga_temperature integer ,
cortex_misc_alarm integer,
project_id integer ,
software_id integer,
hardware_id integer,
select_freq_vcxo integer CHECK(select_freq_vcxo BETWEEN 0 AND 14),
timetag_coding integer CHECK(timetag_coding IN(0,1,2,3,4,5)),
timetag_firstf integer ,
time_tagsecondf float,
irigb_nasa36 integer CHECK(irigb_nasa36  IN(0,1,2)),
tcpip_mon_clients integer,
tcpip_control_clients integer,
tcpip_simulated_clients integer,
tcpip_tele_clients integer,
tcpip_rang_clients_rng integer,
tcpip_rang_clients_meas integer,
tcpip_log_clients integer,
tcpip_spect_clients integer,
tcpip_doppvect_clients integer,
reserved integer,
tcip_other_clients integer,
reserved1 integer,
tcpip_telemetrya_client integer,
tcpip_telemetryb_client integer,
tcpip_telemetryc_client integer,
tcpip_telemetryd_client integer,
tcpip_telemetrye_client integer,
tcpip_telemetryf_client integer,
tcpip_telemetryg_client integer,
tcpip_telemetryh_client integer,
crt_extension integer,
cortex_neuronflows integer,
global_crtoptions integer
);